const USER_LOGIN = "USER_LOGIN";
const USER_REGISTRATION = "USER_REGISTRATION";
const USER_LOGOUT = "USER_LOGOUT";
const RESET_STATE = "RESET_STATE";

export { USER_LOGIN, USER_REGISTRATION, USER_LOGOUT, RESET_STATE };
